sudo: required
services:
  - docker

before_install:
  - docker build -t gksbrandon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gksbrandon/react-test npm test -- --coverage

after_success:
  - docker build -t gksbrandon/multi-client ./client
  - docker build -t gksbrandon/multi-nginx ./nginx
  - docker build -t gksbrandon/multi-server ./server
  - docker build -t gksbrandon/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gksbrandon/multi-client
  - docker push gksbrandon/multi-nginx
  - docker push gksbrandon/multi-server
  - docker push gksbrandon/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-176357753726"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"